vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        wine:
            uri_prefix: /uploads/wine
            upload_destination: '%kernel.project_dir%/public/uploads/wine'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
